apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins
spec:
  selector:
    matchLabels:
      run: my-jenkins
  replicas: 1
  template:
    metadata:
      labels:
        run: my-jenkins
    spec:
      containers:
      - name: my-jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: my-jenkins-svc
  labels:
    run: my-jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30008
    protocol: TCP
  selector:
    run: my-jenkins
