apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx-app
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: sanaulhasan/nginx-app:latest
        ports:
        - containerPort: 80
---


apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc2
  labels:
    run: my-nginx-svc2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: nginx-app
