apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx-deployment
  labels:
    app: application
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-application
        image: sanaulhasan/nginx-app:latest
        ports:
        - containerPort: 80
#      imagePullPolicy: Always
---


apiVersion: v1
kind: Service
metadata:
  name: application-nginx-svc
  labels:
    run: my-nginx-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: nginx-app
